site_name: OppoT2 Documentation

repo_url: https://github.com/ZacheryCalahan/OppoT2
repo_name: ZacheryCalahan/OppoT2
nav:
  - Home: index.md
  - CPU:
    - CPU Overview: cpu/index.md
    - ISA Design: cpu/isa.md
    - Instructions: cpu/instructions.md
    - Conventions: cpu/conventions.md
  - Assembler: 
    - Assembler Overview: asm/index.md

theme:
  name: material
  palette:
    scheme: slate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  