site_name: OppoT2 Documentation

nav:
  - Home: index.md
  - CPU:
    - CPU Overview: cpu/index.md
    - ISA Design: cpu/isa.md
    - Instructions: cpu/instructions.md
  - Assembler: 
    - Assembler Overview: asm/index.md

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - asm
    - c
    - c#


  